### ISSUE TITLE
AttributeError: FanShim instance has no attribute 'stop'

### ISSUE THREAD

**Issue by botto** [pimoroni/fanshim-python#1]
So I get a complaint that stop doesn't exist. I'm curious, what is stop supposed to do?

https://github.com/pimoroni/fanshim-python/blob/07febafcb968ce6a5c575bd436e67799b5e325a4/library/fanshim/__init__.py#L119

**Comment by Shoe-Pi** [comment]
At exit it calls the `stop` function which doesn't seem to exist.  Meant to be GPIO cleanup presumably?

**Comment by Gadgetoid** [comment]
Hopefully fixed in v0.0.2 - `stop` was the original name for `stop_polling` so the polling thread would exit cleanly. This error was probably blocking the `atexit` call that cleans up the LEDs too.
