### ISSUE TITLE
Fan operating continuously, can't control it (or the LED) with fanshim

### ISSUE THREAD

**Issue by outs1der** [pimoroni/fanshim-python#103]
After a recent update on my Raspberry Pi 4 the fan operates continuously irrespective of the status of the fanshim service.

Have uninstalled and re-installed the software a few times, no change. 

Also through Python I cannot control the fan or the LED. get_fan method returns 1 or 0 and seems to toggle correctly, but the fan just keeps running

Seems like some fairly fundamental issue here but I'm unable to diagnose. Have followed the install instructions, and the service appears functional when installed.

Linux pi 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux

**Comment by Gadgetoid** [comment]
Sorry for the delay responding- any change since? This is usually the result of a poor connection between the shim and the GPIO.
