### ISSUE TITLE
Default GPIO Pins

### ISSUE THREAD

**Issue by dommy1C** [pimoroni/fanshim-python#105]
Hi

Do I have to use the default pins : 17 and 18?

It interferes with my UPS Hat you see.  How could I change it and how (if possible)

Thanks

**Comment by Gadgetoid** [comment]
You would have to remove Fan SHIM from the Pi's GPIO and wire it manually, pinout here: https://pinout.xyz/pinout/fan_shim

Then the `FanShim` constructor can accept alternate fan control and button pins - https://github.com/pimoroni/fanshim-python/blob/33abcde2d51944e6dcb3bc2ecbddb251f65eb79a/library/fanshim/__init__.py#L11
