### ISSUE TITLE
commands work but fan doesn't start

### ISSUE THREAD

**Issue by dchmelik** [pimoroni/fanshim-python#106]
On Slackware-ARM32 15 Raspberry Pi 4, installation (after uncommenting Debian CODENAME lines from current commit install.sh) and commands work, but don't actually start fan.  Here's output.  Should I paste installation log also?  Maybe it only works on RaspiOS?
```
root@1.darwinheim:~# python3
Python 3.9.10 (main, Jan 17 2022, 21:15:54) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fanshim import FanShim
>>> fanshim = FanShim()
>>> fanshim.set_fan(True)
True
```

**Comment by dchmelik** [comment]
This wasn't completed!

**Comment by dchmelik** [comment]
This wasn't completed!

**Comment by Gadgetoid** [comment]
If it's not Raspberry Pi OS I'm afraid I can't be of much help. If we support one alternate OS we'd have to support them all. Sorry.

The fan should default to on, IIRC, though, so you might have a service or driver that's messing with BCM 18 and preventing control. This library is just toggling a GPIO pin.
