### ISSUE TITLE
LED purple and does not shutdown

### ISSUE THREAD

**Issue by Spanishu** [pimoroni/fanshim-python#45]
Running Famshim since yesterday on a R4 with Raspbian buster. The LED ist now constantly purple. EVen with a service shutdown the led remains on. Any suggestion?

**Comment by Gadgetoid** [comment]
The LED is "smart" so it'll hold whatever colour was last successfully sent to it. You can try running some of the individual examples to see if they affect the LED. It's possible you just have a flaky GPIO connection so the pin-twiddling isn't getting through.
