### ISSUE TITLE
fails to install

### ISSUE THREAD

**Issue by FlorinAndrei** [pimoroni/fanshim-python#51]
How to reproduce:

RPi 4
Raspbian Buster Lite September 2019

Fresh, default OS install. Applied the latest updates and patches. Installed git, python-pip and python3-pip

Cloned this repo. As root, ran ./install.sh

There are no apparent errors. But the service is not actually installed. systemctl does not report anything named like it. Reboot - nothing. Doesn't work.

Tried twice from scratch. Always same result.

---

I had it working before on the same hardware. I believe it was the previous version of Raspbian, and the install was not quite so fresh and default (had been playing a while with Python data science stuff and Tensorflow).

**Comment by Gadgetoid** [comment]
For the service, you need to drop into examples and run `./install-service.sh`

https://github.com/pimoroni/fanshim-python/blob/master/examples/install-service.sh
