### ISSUE TITLE
after shutdown raspberry, fan turns on

### ISSUE THREAD

**Issue by albertux** [pimoroni/fanshim-python#57]
After shutdown the raspberry, fan turns on

**Comment by Gadgetoid** [comment]
The fan is on-by-default so if it receives power from the Pi it will run. This is by design. You would need to use some method to cut power to your Pi for it to be truly off.

See #31 for related discussion.

**Comment by grayerbeard** [comment]
Or some quite simple code to operate GPIO 18.
