### ISSUE TITLE
Executable path is not absolute

### ISSUE THREAD

**Issue by matteos1** [pimoroni/fanshim-python#66]
git clone https://github.com/pimoroni/fanshim-python
cd fanshim-python
sudo ./install.sh

cd examples
sudo ./install-service.sh --on-threshold 50 --off-threshold 40 --delay 2

this is the error when i try to start the service

Feb 15 20:03:41 DietPi systemd[1]: [/etc/systemd/system/pimoroni-fanshim.service:8] Executable path is not absolute, ignoring: python3 /root/fanshim-python/exam
ples/automatic.py --on-threshold 50 --off-threshold 40 --delay 2 --brightness 255
Feb 15 20:03:41 DietPi systemd[1]: pimoroni-fanshim.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 20:03:41 DietPi systemd[1]: [/etc/systemd/system/pimoroni-fanshim.service:8] Executable path is not absolute, ignoring: python3 /root/fanshim-python/exam
ples/automatic.py --on-threshold 50 --off-threshold 40 --delay 2 --brightness 255
Feb 15 20:03:41 DietPi systemd[1]: pimoroni-fanshim.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 20:03:51 DietPi systemd[1]: [/etc/systemd/system/pimoroni-fanshim.service:8] Executable path is not absolute, ignoring: python3 /root/fanshim-python/exam
ples/automatic.py --on-threshold 50 --off-threshold 40 --delay 2 --brightness 255
Feb 15 20:03:51 DietPi systemd[1]: pimoroni-fanshim.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
Feb 15 20:03:52 DietPi systemd[1]: [/etc/systemd/system/pimoroni-fanshim.service:8] Executable path is not absolute, ignoring: python3 /root/fanshim-python/exam
ples/automatic.py --on-threshold 50 --off-threshold 40 --delay 2 --brightness 255
Feb 15 20:03:52 DietPi systemd[1]: pimoroni-fanshim.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.

**Comment by Gadgetoid** [comment]
I think that must have been regressed by https://github.com/pimoroni/fanshim-python/pull/43/files

I'll see what I can do to fix it without having to roll everything back.
