### ISSUE TITLE
FanShim on Raspberry Pi 4

### ISSUE THREAD

**Issue by rei-vilo** [pimoroni/fanshim-python#72]
I tried FanShim on a Raspberry Pi 4 and it doesn't work as expected:

+ Despite launching the Python service with default parameters, _ie._ `--off-threshold 55 --on-threshold 66`, the fan is always on, even when temperature = 28 °C

+ LED doesn't work, even when playing with the `python3 fanshim-python/examples/led.py example.

I went through #3, but how to configure the FanShim correctly for the Raspberry Pi 4?

I also checked #5, but UART isn't enabled (no `enable_uart=1` in my `/boot/config.txt`).

The [product page](https://shop.pimoroni.com/products/fan-shim) advertises about the Raspberry Pi 4 but the [Getting Started with Fan SHIM](https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-fan-shim) doesn't offer any specifics. 

Thank you for your help.

**Comment by rei-vilo** [comment]
+ **uname**
```
$ uname -a
Linux myPiFour 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
```

+ **RPi.GPIO**
```
>>> import RPi.GPIO as GPIO
>>> GPIO.VERSION
'0.7.0'
```

**Comment by Gadgetoid** [comment]
I'd be inclined to believe this is a contact/electrical issue, do you get fan response/LED output if you run these examples while gently tilting the Fan SHIM in an effort to get better GPIO contact?

**Comment by rei-vilo** [comment]
Thank you for your suggestion. Indeed, gently titling the FanSHIM solves the issue, alas as long as I use my finder. How to get a permanent solution without requiring a finger?

**Comment by EGMSSE** [comment]
Yes, I am having the same issue. The shim itself is advertised as being able to make contact via "friction fitting". However, I have to gently apply pressure to it in just the right way to get the fan to react as expected, i.e., turn on and off, get the led to respond appropriately.

A solution that does not require soldering would be ideal. But I can confirm the friction fitting is not working for me with an RPi4

**Comment by Gadgetoid** [comment]
Sometimes the Pi's GPIO can be bent by adding/removing HATs and correcting this can help.

Additionally, the manufacturing tolerance of the friction-fit header isn't perfect; we've shipped a lot of Fan SHIM units and issues are few and far between, but they happen. We're usually happy to try swapping your Fan SHIM out for another one if all else fails.

**Comment by jameselks** [comment]
I had the same problem - bending the pins out very slightly fixed it. Thanks!

**Comment by EGMSSE** [comment]
yeah...VERY slightly, right?!

I actually used a plant lens that I had sitting around to better see how much each was bent. I'd imagine if you had one of those fancy jeweler's lenses that can be worn on the face and used hands free would be the best.

Glad I could help

**Comment by dpd73** [comment]
I too found the LED wouldn't work unless I fiddled with the pins (used a fingernail!) then the LED appeared. Can be a bit temperamental. The button and fan worked fine. Guess that's the drawback of being friction fit.
