### ISSUE TITLE
Install FanShim using Ansible

### ISSUE THREAD

**Issue by fourstepper** [pimoroni/fanshim-python#90]
I've made a little role for installing and activating FanShim via Ansible - would this perhaps be helpful as an "alternative installation" method?

You can find the role here: https://gitlab.com/ansible-opletal/ansible-role-fanshim

Thanks

**Comment by Gadgetoid** [comment]
Thank you - making this "notice" and keeping open for posterity!

**Comment by fourstepper** [comment]
This is in fact quite old and not really well supported across distributions... I think I will just close this one out, but the code that's there can be used as a base in the future :)

**Comment by Gadgetoid** [comment]
Thank you! I don't know the first thing about Ansible so I'd have left this open, oblivious to that fact.

**Comment by fourstepper** [comment]
Completely understandable :)
