### ISSUE TITLE
LED control doesn't appear to work

### ISSUE THREAD

**Issue by jimklo** [pimoroni/fanshim-python#94]
Trying to create my own variant of the service that controls the led in a different manner.

Finding that the library doesn't seem to alter how the LED functions.

```
import fanshim import FanShim

fs = FanShim()
fs.set_light(0, 0, 0, brightness=0)  # assuming this should turn it off, however led stays lit.
fs.set_light(255, 0, 0, brightness=0.5) # assuming this should turn the led red, at about 50%  brightness, however led stays lit white.
```

Note that I've looked at #5 and noted that `uart_enabled=1` does exist in my `/boot/config.txt`, which is required to use the MMDVM_HS_DUAL HAT I'm using.  I've tried reseating the shim, but it seems like that is not the issue.

FWIW fan control and button control does work, so far the LED seems to be the only issue.

**Comment by jimklo** [comment]
Okay, I think I may know what's going on.  Looking at the [shim pinout](https://pinout.xyz/pinout/fan_shim) and comparing with the 
![MMDVM_HS_DUAL pinout](https://user-images.githubusercontent.com/588760/103819145-b1f81a80-501e-11eb-9f52-3580b848ad27.png), I'm seeing that there is a conflict with GPIO 14/15.  Not sure if there is a way to modify the shim to make this work short of having another shim board and wiring to a pair of unused GPIO pins.

**Comment by Gadgetoid** [comment]
Some trace cutting and careful bodge wire soldering might work, but otherwise you'd have to spin the fan shim around, wire up to the header manually and find some way to secure it to the board.

I think in the time since we originally created Fan SHIM the Pi 4's thermal management has been "fixed" anyway, so it's probably redundant.
